### ISSUE TITLE
Error message is shown up after record was successfully updated

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/odata-component#28]
Preconditions: Record with ``` "No": "58" ``` and ``` "Name": "qweqwe" ``` is already created.

STR:
1. Create flow with trigger (timer)
2. Set odata-component as 2nd step.
3.  Select credentials of eio NAV instance.
4. Choose "Upsert entry" action and select "CustomerCardService"
5. Input in dev mode ``` {
  "No": "58",
  "Name": "update_test"
} ``` 

AR: 

1. Error is shown: ``` Error! Cannot set property 'isNew' of undefined ```
2. Logs ``` TypeError: Cannot set property 'isNew' of undefined
    at GenericODataClient.upsertObjectById (/app/lib/commons/odata/ODataClient.js:183:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) ```

ER: 

1. Sample is retrieved with no error message.
2. Record is updated.

**Comment by jhorbulyk** [comment]
Can you share the full log with me?  I can't reproduce...

**Comment by stas-fomenko** [comment]
runtime log:
```
[2018-08-30 16:56:59.076]: Starting application in apprunner
[2018-08-30 16:56:59.078]: Starting slug download ...
[2018-08-30 16:57:00.470]: Successfully downloaded and extracted slug file
[2018-08-30 16:57:00.471]: Writing config vars to .profile.d/config_vars
[2018-08-30 16:57:00.495]: Detected 256 MB available memory
[2018-08-30 16:57:00.495]: Detected 0.1 CPU available
[2018-08-30 16:57:00.497]: Starting the application with node ./node_modules/elasticio-sailor-nodejs/run.js
[2018-08-30 16:57:01.006]: {"name":"sailor","hostname":"42ff100e7716","pid":7,"ELASTICIO_TASK_ID":"5b863f676d19500012481b8c","ELASTICIO_EXEC_ID":"706508a85c44439692690fba182c1321","ELASTICIO_STEP_ID":"step_2","ELASTICIO_COMP_ID":"5ad86cb6e2301d0007036fcc","ELASTICIO_FUNCTION":"upsertObject","tag":"5b863f676d19500012481b8c","level":30,"msg":"About to initialize component for execution","time":"2018-08-30T13:57:01.006Z","v":0}
[2018-08-30 16:57:01.061]: invokeModuleFunction – init is not found
[2018-08-30 16:57:01.061]: {"name":"sailor","hostname":"42ff100e7716","pid":7,"ELASTICIO_TASK_ID":"5b863f676d19500012481b8c","ELASTICIO_EXEC_ID":"706508a85c44439692690fba182c1321","ELASTICIO_STEP_ID":"step_2","ELASTICIO_COMP_ID":"5ad86cb6e2301d0007036fcc","ELASTICIO_FUNCTION":"upsertObject","tag":"5b863f676d19500012481b8c","level":30,"msg":"Component execution initialized successfully","time":"2018-08-30T13:57:01.061Z","v":0}
[2018-08-30 16:57:01.079]: {"name":"sailor","hostname":"42ff100e7716","pid":7,"ELASTICIO_TASK_ID":"5b863f676d19500012481b8c","ELASTICIO_EXEC_ID":"706508a85c44439692690fba182c1321","ELASTICIO_STEP_ID":"step_2","ELASTICIO_COMP_ID":"5ad86cb6e2301d0007036fcc","ELASTICIO_FUNCTION":"upsertObject","tag":"5b863f676d19500012481b8c","level":30,"deliveryTag":1,"messageId":"65bc8cdc-1d68-474f-9b79-8a869114ad8e","parentMessageId":"65bc8cdc-1d68-474f-9b79-8a869114ad8e","traceId":"8c5607a3-32b8-4a05-a3ea-4d6fed4e055f","messagesCount":1,"messageProcessingTime":0,"msg":"processMessage received","time":"2018-08-30T13:57:01.079Z","v":0}
[2018-08-30 16:57:01.081]: Will perform update to CustomerCardService with id '58'
[2018-08-30 16:57:01.082]: Making PATCH request to https://nav-docker-vm.westus2.cloudapp.azure.com:7048/nav/odata/CustomerCardService('58') ...
[2018-08-30 16:57:01.767]: TypeError: Cannot set property 'isNew' of undefined
[2018-08-30 16:57:01.768]: {"name":"sailor","hostname":"42ff100e7716","pid":7,"ELASTICIO_TASK_ID":"5b863f676d19500012481b8c","ELASTICIO_EXEC_ID":"706508a85c44439692690fba182c1321","ELASTICIO_STEP_ID":"step_2","ELASTICIO_COMP_ID":"5ad86cb6e2301d0007036fcc","ELASTICIO_FUNCTION":"upsertObject","tag":"5b863f676d19500012481b8c","level":30,"deliveryTag":1,"messageId":"65bc8cdc-1d68-474f-9b79-8a869114ad8e","parentMessageId":"65bc8cdc-1d68-474f-9b79-8a869114ad8e","traceId":"8c5607a3-32b8-4a05-a3ea-4d6fed4e055f","messagesCount":1,"err":{"message":"Cannot set property 'isNew' of undefined","name":"TypeError","stack":"TypeError: Cannot set property 'isNew' of undefined\n    at GenericODataClient.upsertObjectById (/app/lib/commons/odata/ODataClient.js:183:27)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"},"messageProcessingTime":688,"msg":"processMessage emit error","time":"2018-08-30T13:57:01.768Z","v":0}
[2018-08-30 16:57:01.768]: at <anonymous>
[2018-08-30 16:57:01.768]: at GenericODataClient.upsertObjectById (/app/lib/commons/odata/ODataClient.js:183:27)
[2018-08-30 16:57:01.769]: at process._tickCallback (internal/process/next_tick.js:188:7)
[2018-08-30 16:57:01.771]: {"name":"sailor","hostname":"42ff100e7716","pid":7,"ELASTICIO_TASK_ID":"5b863f676d19500012481b8c","ELASTICIO_EXEC_ID":"706508a85c44439692690fba182c1321","ELASTICIO_STEP_ID":"step_2","ELASTICIO_COMP_ID":"5ad86cb6e2301d0007036fcc","ELASTICIO_FUNCTION":"upsertObject","tag":"5b863f676d19500012481b8c","level":30,"deliveryTag":1,"messageId":"65bc8cdc-1d68-474f-9b79-8a869114ad8e","parentMessageId":"65bc8cdc-1d68-474f-9b79-8a869114ad8e","traceId":"8c5607a3-32b8-4a05-a3ea-4d6fed4e055f","messagesCount":0,"errorCount":1,"promises":1,"messageProcessingTime":692,"msg":"processMessage emit end","time":"2018-08-30T13:57:01.771Z","v":0}
[2018-08-30 16:57:53.523]: Received SIGTERM
[2018-08-30 16:57:53.528]: Disconnecting
[2018-08-30 16:57:53.541]: Successfully disconnected
[2018-08-30 16:57:53.541]: [INFO  tini (1)] Spawned child process '/runner/init' with pid '7'
[2018-08-30 16:57:53.542]: [INFO  tini (1)] Main child exited normally (with status '0')
```

**Comment by stas-fomenko** [comment]
retrieve sample log:
```
Starting your Docker container ...
Starting application in apprunner
Starting slug download ...
Successfully downloaded and extracted slug file
Writing config vars to .profile.d/config_vars
Detected 256 MB available memory
Detected 0.1 CPU available
Starting the application with node ./node_modules/elasticio-sailor-nodejs/run.js
{"name":"sailor","hostname":"562fd2bff126","pid":7,"ELASTICIO_TASK_ID":"5b87f8646d19500012484341","ELASTICIO_EXEC_ID":"69df6ffbb4b5483abf9511bd78d8d4a3","ELASTICIO_STEP_ID":"step_2","ELASTICIO_COMP_ID":"5ad86cb6e2301d0007036fcc","ELASTICIO_FUNCTION":"upsertObject","tag":"5b87f8646d19500012484341","level":30,"msg":"About to initialize component for execution","time":"2018-08-30T14:00:14.146Z","v":0}
invokeModuleFunction – init is not found
{"name":"sailor","hostname":"562fd2bff126","pid":7,"ELASTICIO_TASK_ID":"5b87f8646d19500012484341","ELASTICIO_EXEC_ID":"69df6ffbb4b5483abf9511bd78d8d4a3","ELASTICIO_STEP_ID":"step_2","ELASTICIO_COMP_ID":"5ad86cb6e2301d0007036fcc","ELASTICIO_FUNCTION":"upsertObject","tag":"5b87f8646d19500012484341","level":30,"msg":"Component execution initialized successfully","time":"2018-08-30T14:00:14.203Z","v":0}
Starting application in apprunner
Starting slug download ...
Successfully downloaded and extracted slug file
Writing config vars to .profile.d/config_vars
Detected 256 MB available memory
Detected 0.1 CPU available
Starting the application with node ./node_modules/elasticio-sailor-nodejs/run.js
Initializing component for execution
{"name":"sailor","hostname":"1c3376f40597","pid":7,"ELASTICIO_TASK_ID":"5b87f8646d19500012484341","ELASTICIO_EXEC_ID":"69df6ffbb4b5483abf9511bd78d8d4a3","ELASTICIO_STEP_ID":"mapper:step_1:step_2","ELASTICIO_COMP_ID":"557aee0d5925ab0900000002","ELASTICIO_FUNCTION":"jsonataMap","tag":"5b87f8646d19500012484341","level":30,"deliveryTag":1,"messageId":"02588277-99cc-48f2-a3af-1dcc5e9b414e","parentMessageId":"unknown","traceId":"869c5d2c-0c18-405e-b9ae-750f50ac0f12","messagesCount":1,"messageProcessingTime":0,"msg":"processMessage received","time":"2018-08-30T14:00:47.956Z","v":0}
{"name":"app","hostname":"1c3376f40597","pid":7,"level":30,"conf":{"condition":null,"mapper":"{\n  \"No\": \"58\",\n  \"Name\": \"qweqwe\"\n}"},"body":{"fireTime":"3719-07-21T11:18:18.507Z"},"msg":"Received new message with body and config","time":"2018-08-30T14:00:47.959Z","v":0}
{"name":"app","hostname":"1c3376f40597","pid":7,"level":30,"msg":"About to process message...","time":"2018-08-30T14:00:47.959Z","v":0}
{"name":"app","hostname":"1c3376f40597","pid":7,"level":30,"expression":"{\n  \"No\": \"58\",\n  \"Name\": \"qweqwe\"\n}","msg":"Evaluating string expression","time":"2018-08-30T14:00:47.959Z","v":0}
{"name":"app","hostname":"1c3376f40597","pid":7,"level":30,"body":{"No":"58","Name":"qweqwe"},"msg":"Message processed, going to emit","time":"2018-08-30T14:00:47.961Z","v":0}
{"name":"sailor","hostname":"1c3376f40597","pid":7,"ELASTICIO_TASK_ID":"5b87f8646d19500012484341","ELASTICIO_EXEC_ID":"69df6ffbb4b5483abf9511bd78d8d4a3","ELASTICIO_STEP_ID":"mapper:step_1:step_2","ELASTICIO_COMP_ID":"557aee0d5925ab0900000002","ELASTICIO_FUNCTION":"jsonataMap","tag":"5b87f8646d19500012484341","level":30,"deliveryTag":1,"messageId":"02588277-99cc-48f2-a3af-1dcc5e9b414e","parentMessageId":"unknown","traceId":"869c5d2c-0c18-405e-b9ae-750f50ac0f12","messagesCount":1,"messageProcessingTime":6,"msg":"processMessage emit data","time":"2018-08-30T14:00:47.962Z","v":0}
{"name":"sailor","hostname":"1c3376f40597","pid":7,"ELASTICIO_TASK_ID":"5b87f8646d19500012484341","ELASTICIO_EXEC_ID":"69df6ffbb4b5483abf9511bd78d8d4a3","ELASTICIO_STEP_ID":"mapper:step_1:step_2","ELASTICIO_COMP_ID":"557aee0d5925ab0900000002","ELASTICIO_FUNCTION":"jsonataMap","tag":"5b87f8646d19500012484341","level":30,"deliveryTag":1,"messageId":"02588277-99cc-48f2-a3af-1dcc5e9b414e","parentMessageId":"unknown","traceId":"869c5d2c-0c18-405e-b9ae-750f50ac0f12","messagesCount":0,"errorCount":0,"promises":1,"messageProcessingTime":10,"msg":"processMessage emit end","time":"2018-08-30T14:00:47.966Z","v":0}
{"name":"sailor","hostname":"562fd2bff126","pid":7,"ELASTICIO_TASK_ID":"5b87f8646d19500012484341","ELASTICIO_EXEC_ID":"69df6ffbb4b5483abf9511bd78d8d4a3","ELASTICIO_STEP_ID":"step_2","ELASTICIO_COMP_ID":"5ad86cb6e2301d0007036fcc","ELASTICIO_FUNCTION":"upsertObject","tag":"5b87f8646d19500012484341","level":30,"deliveryTag":1,"messageId":"38bc415f-4c47-4720-ae4c-48ee7f593e0d","parentMessageId":"02588277-99cc-48f2-a3af-1dcc5e9b414e","traceId":"869c5d2c-0c18-405e-b9ae-750f50ac0f12","messagesCount":1,"messageProcessingTime":0,"msg":"processMessage received","time":"2018-08-30T14:00:47.972Z","v":0}
Making GET request to https://nav-docker-vm.westus2.cloudapp.azure.com:7048/nav/odata/$metadata ...
Will perform update to CustomerCardService with id '58'
Making PATCH request to https://nav-docker-vm.westus2.cloudapp.azure.com:7048/nav/odata/CustomerCardService('58') ...
TypeError: Cannot set property 'isNew' of undefined
at GenericODataClient.upsertObjectById (/app/lib/commons/odata/ODataClient.js:183:27)
TypeError: Cannot set property 'isNew' of undefined
    at GenericODataClient.upsertObjectById (/app/lib/commons/odata/ODataClient.js:183:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
at <anonymous>
at GenericODataClient.upsertObjectById (/app/lib/commons/odata/ODataClient.js:183:27)
at process._tickCallback (internal/process/next_tick.js:188:7)
{"name":"sailor","hostname":"562fd2bff126","pid":7,"ELASTICIO_TASK_ID":"5b87f8646d19500012484341","ELASTICIO_EXEC_ID":"69df6ffbb4b5483abf9511bd78d8d4a3","ELASTICIO_STEP_ID":"step_2","ELASTICIO_COMP_ID":"5ad86cb6e2301d0007036fcc","ELASTICIO_FUNCTION":"upsertObject","tag":"5b87f8646d19500012484341","level":30,"deliveryTag":1,"messageId":"38bc415f-4c47-4720-ae4c-48ee7f593e0d","parentMessageId":"02588277-99cc-48f2-a3af-1dcc5e9b414e","traceId":"869c5d2c-0c18-405e-b9ae-750f50ac0f12","messagesCount":0,"errorCount":1,"promises":2,"messageProcessingTime":2092,"msg":"processMessage emit end","time":"2018-08-30T14:00:50.064Z","v":0}
Received SIGTERM
Disconnecting
Successfully disconnected
[INFO  tini (1)] Main child exited normally (with status '0')
[INFO  tini (1)] Spawned child process '/runner/init' with pid '7'
Disconnecting
Received SIGTERM
Successfully disconnected
[INFO  tini (1)] Spawned child process '/runner/init' with pid '7'
[INFO  tini (1)] Main child exited normally (with status '0')
```

**Comment by jhorbulyk** [comment]
I was able to eventually be able to reproduce this sporatically.  It looks like a NAV bug but I implemented a workaround in the component in this commit: https://github.com/elasticio/odata-component/commit/06cdaf4d01e94648f7a07a92552f7385bbabac87

**Comment by stas-fomenko** [comment]
tested
